### PR TITLE
lodash & test-stack added 

### PR DESCRIPTION
**Pull request by gbaumgart**
hi,
I added only lodash (included in builds for now) and some boiler-stuff to run test-units.
greets

### CODE REVIEW

**Comment by Lochemage** [comment]
@gbaumgart 

I'm going to try and get to this one over the weekend, but things are very busy for me right now.

**Comment by Lochemage** [comment]
@gbaumgart 

I've merged it in, looking forward to building some tests for it!  Do you know how to provide code coverage reports for this as well?

**Comment by gbaumgart** [comment]
not really, but it does such thing : https://theintern.github.io/intern/#reporter-results. i try to get it in the next PR

**Comment by gbaumgart** [comment]
Doing tests is prepared in Code/tests/basics/* . But you must add your new units in Code/tests/intern/intern.js

**Pull request merged**
