### PR TITLE
make wcDocker classes as option

### PR DESCRIPTION
**Pull request by gbaumgart**
Hi,
here a PR which makes overriding wcDockerClasses more easy and clean. In short: an API consumer 
can pass the pointers to his class overrides as option to new wcDocker: 

var options = {
  'wcPanel':myPanelClass
}

the downside/change in wcDocker and other modules: 

instead of "new wcPanel(type,option)", you need to call new (this.option('wcPanel'))(type,options)

I only changed this for wcPanel, wcFrame and wcSplitter everywhere (no interest in other classes). 

This was the only clean way to enable subclassing from outside without changing wcDocker files. Not sure you will agree or like it; let me know. The other options would have been require-js-Module-Configs or remapping or dirty prototype patches.

Else, this.option(what) is done in wcDocker/base. It will search in the instance's option and falls back to the holding docker's options. 

its tested and works. I am still looking at a more clean class factory function....
g

### CODE REVIEW

**Comment by gbaumgart** [comment]
Hi,
anything I've to do? Not sure what's meant by 'conflicts' here. However, If you think, its bad, let me know. I will need optional classes in the options for better templating and subclassing...

**Comment by Lochemage** [comment]
@gbaumgart 

I have not yet had a chance to look at this deeply, but by looking at your change log I do have a couple of suggestions:

- Can we rename the properties added to `docker._options`, using options like `docker._options.wcSplitter` might not clearly explain that the option is actually a default class name rather than the actual object itself. Something like `docker._options.wcSplitterClass` or maybe `docker._options.classNames.wcSplitter` even.
- I would also like you to add `wcLayout` as a class type so people will be able to select the global default layout class.
- Not sure what that final line change is for indexDev.html: 
`tutorials: location.href.indexOf('noTutorials')!=-1 ? false : true`. Did you mean for this to be temporary?

**Comment by gbaumgart** [comment]
ah, great! let me fix that, thanks!
?noTutorials is great for devs like me who sit somewhere in the deep mountains with awful or no internet ;-) It takes 2-3 minutes to load the tutorial/docs page here...

**Comment by Lochemage** [comment]
@gbaumgart 

Ah, then it's fine to keep it in there, I'm sure it will be useful for me as well as it does take up significant time loading.

**Comment by gbaumgart** [comment]
ok, i did end up with:
this._getClass('wcPanel') to get the rmodule from _options.classNames. In base this would be: 
_getClass:function(name){
            return this.getOptions()['classNames'][name];
        }

and applied this looks like:

this._splitter = new (this._getClass('wcSplitter'))(docker.$container, this, this._orientation);

i whish the constructor signature would be the always the same, so we have a function:

this.create(what,options,where); 

i tried that but no, fails somewhere deep. 

however, if its ok now to you, i would replace everywhere new wClass with
new (this._getClass('wcSplitter'))(...);

then, I am aware about extra code, I can also do some optimizations to reduce code size, there much left open:

for instance:
multiple calls within a function to things like "this._parent" would be replaced by:

var parent = this._parent;

then later you only use parent. uglify doesn't do that automatically...

**Comment by Lochemage** [comment]
@gbaumgart 

Thanks for the update. I have a question, even though you are making it much more dynamic to setup default class names, how well does this actually work with the DCL architecture?  You still have to pass the class definition object as a parameter, so changing the default class name will not even work unless you also change the module code. Unless I am missing something?

Also, the `var parent = this._parent` change I feel is not really necessary.  If optimization is what you are aiming for, I don't really see any benefit here; You are trading a lookup for a value that is directly inside the `this` pointer for allocating and later deallocating a temporary variable that is assigned to the looked up property value. In this case the extra overhead of creating a new variable that will immediately need cleaning up seems like a much heavier operation than just looking up a variable a few times. What do you think?

**Comment by gbaumgart** [comment]
I don't know much about dcl but since you only pass a valid module, a subclass of the original if you like, it should be the same to dcl. The problem is rather in require-js; you can only place module mappings but no variations of the original, in that users just write in options:
classNames.wcDocker = dcl([wcPanel],{
  ...impl...
})

'parent', ok, didnt know that. just thought resolving the lookup is way easier than going over 'this' expressions.

**Comment by gbaumgart** [comment]
ok, i updated all in a new PR: https://github.com/WebCabin/wcDocker/pull/73

**Pull request closed without merging**
